name: 构建前端并发布

on:
  push:
    tags:
      - 'v*' # 当推送版本标签时触发 (例如 v1.0.0)
  workflow_dispatch:  # 添加这行以支持手动触发
    inputs:
      version:
        description: '输入版本号（如 v1.0.0）'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./client
        run: pnpm install

      - name: Build frontend
        working-directory: ./client
        run: pnpm build

      - name: Archive dist folder
        run: |
          cd client
          zip -r dist.zip dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: client/dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
